### ISSUE TITLE
Check the `superbuild-ros2` build

### ISSUE THREAD

**Issue by valegagge** [icub-tech-iit/docker-deployment-images#1]
The 'superbuild-ros2' image has build error, as you can see here.

We'd like to fix that errors.

**Dod**
The errors are fixed

cc @Nicogene

**Comment by Nicogene** [comment]
@valegagge where I can find the error or the log of the action?

**Comment by valegagge** [comment]
> @valegagge where I can find the error or the log of the action?

[Here ](https://github.com/icub-tech-iit/docker-deployment-images/actions/runs/3959958568/jobs/6783472629#step:11:153)

**Comment by Nicogene** [comment]
It is strange because the error seems something similar to this one: https://askubuntu.com/questions/1153047/could-not-reslove-packages-ros-org-ros but we are starting from an official ros image (https://hub.docker.com/layers/library/ros/foxy-ros-core/images/sha256-059bdcd9c674d82d5a5a037a55d565c6e6252e3e00bef30005b753d9538c4df7?context=explore)

**Comment by MSECode** [comment]
I'm gonna close the issue since the error is now solved. It was due to the re-building of icub-main using some options that are now deprecated.
