### ISSUE TITLE
Check usage of docker images built on ubuntu xx working on ubuntu yy and viceversa

### ISSUE THREAD

**Issue by MSECode** [icub-tech-iit/docker-deployment-images#20]
This issue is a placeholder for keeping an analysis of possible misbehaviors for images built with a specific version of ubuntu, such as ubuntu 22.04, which should than work on a machine running on ubuntu 20.04 or viceversa.
Being docker developed also for such cases, it should not be a problem to do that, and the only thing that we should care about in order to do not have problems is to have the same kernel between docker image and the host.
Anyways, let's keep in this issue all the pieces of information that can be helpful and informative for this problem.

cc: @valegagge

**Comment by valegagge** [comment]
I surfed the internet a little and it seems that it is not important that the ubuntu version of the images differs from the host one because the image doesn't contain the kernel.

See here form more details:
https://stackoverflow.com/questions/33112137/run-different-linux-os-in-docker-container

cc @MSECode

**Comment by MSECode** [comment]
Thanks for the update and for mentioning the thread.

**Comment by valegagge** [comment]
Dod satisfied. Closing
